ALTER TRIGGER TR_PRESTAMO_INSERT 
ON PRESTAMO 
FOR INSERT
AS 
DECLARE @NRO_LIBRO INT
DECLARE @NRO_COPIA INT

BEGIN
	DECLARE C_TRG_PRESTAMO CURSOR FOR
	SELECT PR.NRO_LIBRO, PR.NRO_COPIA
	FROM INSERTED AS PR
	
	OPEN C_TRG_PRESTAMO
	
	fetch next from C_TRG_PRESTAMO
	into @NRO_LIBRO, @NRO_COPIA
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
	    EXEC SP_VALIDAR_ESTADO @NRO_LIBRO, @NRO_COPIA
		fetch next from C_TRG_PRESTAMO
		into @NRO_LIBRO, @NRO_COPIA
	END
	CLOSE C_TRG_PRESTAMO
	DEALLOCATE C_TRG_PRESTAMO
END	


--

ALTER PROCEDURE SP_VALIDAR_ESTADO
@NRO_LIBRO INT,
@NRO_COPIA INT
AS
BEGIN
    --  BEGIN TRANSACTION
    --  BEGIN TRY
    DECLARE @ESTADO_COPIA AS CHAR
    DECLARE @ESTADO_LIBRO AS CHAR

    SET @ESTADO_LIBRO=(
        SELECT ESTADO 
        FROM LIBRO  
        WHERE NRO_LIBRO = @NRO_LIBRO
    )

    SET @ESTADO_COPIA=(
        SELECT ESTADO 
        FROM COPIAS c 
        WHERE NRO_COPIA = @NRO_COPIA AND NRO_LIBRO = @NRO_LIBRO
    )

    IF (@ESTADO_COPIA='N' OR @ESTADO_LIBRO='N' OR @ESTADO_COPIA='P')
	    BEGIN 
	    	RAISERROR ('Error -: Libro o copia no disponible.', 16, 1)
    	END
    ELSE
        BEGIN
            PRINT 'OK- LIBRO o COPIA DISPONIBLE'
            UPDATE COPIAS 
            SET ESTADO='P'
            WHERE NRO_COPIA = @NRO_COPIA AND NRO_LIBRO = @NRO_LIBRO
        END
END

