ALTER TRIGGER TR_PRESTAMO_INSERT 
ON PRESTAMO 
FOR INSERT
AS 
DECLARE @NRO_LIBRO INT
DECLARE @NRO_COPIA INT

BEGIN
	DECLARE C_TRG_PRESTAMO CURSOR FOR
	SELECT PR.NRO_LIBRO, PR.NRO_COPIA
	FROM INSERTED AS PR
	
	OPEN C_TRG_PRESTAMO
	
	fetch next from C_TRG_PRESTAMO
	into @NRO_LIBRO, @NRO_COPIA
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
	    EXEC SP_VALIDAR_ESTADO @NRO_LIBRO, @NRO_COPIA
		fetch next from C_TRG_PRESTAMO
		into @NRO_LIBRO, @NRO_COPIA
	END
	CLOSE C_TRG_PRESTAMO
	DEALLOCATE C_TRG_PRESTAMO
END	


--
