----trigger---
ALTER TRIGGER TR_PRESTAMO_INSERT 
ON PRESTAMO 
FOR INSERT
AS 
DECLARE @NRO_LIBRO INT
DECLARE @NRO_COPIA INT 

BEGIN 
--CURSOR--
DECLARE  C_TRG_PRESTAMO CURSOR FOR
	SELECT PR.NRO_LIBRO , PR.NRO_COPIA 
	FROM INSERTED AS PR
	
OPEN C_TRG_PRESTAMO
	
	fetch next from C_TRG_PRESTAMO
	      into @NRO_LIBRO,@NRO_COPIA
	
	while @@fetch_status =0


EXEC SP_VALIDAR_ESTADO  @NRO_LIBRO, @NRO_COPIA  
		fetch next from C_TRG_PRESTAMO
			into @NRO_LIBRO,@NRO_COPIA
			

			
PRINT 'paso por el trigger' 

END
CLOSE C_TRG_PRESTAMO
deallocate C_TRG_PRESTAMO

		
END